name: publish

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
          scope: '@suzulabo'
          always-auth: true
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - run: pnpm run lint --max-warnings=0
      - run: pnpm run prettier
      - run: pnpm run build

      - run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
